@startuml Container diagram
title Диаграмма контейнеров "Тёплый дом"

top to bottom direction

!include ../templates/C4_Container.puml

' -----------------
' Внешние сущности
' -----------------

Person(user, "Пользователь", "Пользователь умного дома")
Person(support, "Команда поддержки", "Команда по обслуживанию клиентов")
Person(manager, "Команда продажи", "Команда по продажам и маркетингу")

System_Ext(UserDevicesSystem, "Устройства умного дома пользователя")

' --------
' Системы
' --------

System_Boundary(SmartHomeSystem, "Система управления умным домом") {
    ' Контейнеры
    Container(WebApp, "Веб-приложение", "JavaScript и выбранный фреймворк", "Веб-интерфейс для управления умным домом")
    Container(ApiApplication, "Api Application", "GoLang 1.22", "Обрабатывает запросы пользователей")
    ContainerDb(db, "База данных", "PostgreSql 16", "Хранит информацию об устройствах, пользователях и телеметрии")
    Container(broker, "Брокер сообщений", "Kafka", "Пропускает через себя данные о телеметрии")
    Container(streams, "Обработчик (Библиотека)", "Kafka Streams", "Обрабатывает потоки и агрегирует данные в режиме реального времени")

    ' Системы
    System_Boundary(DevicesSystem, "Управление устройствами") {
        Container(DevicesContainer, "Администрирование устройств")
        Container(ModulesContainer, "Администрирование модулей")
    }
    
    System_Boundary(TelemetrySystem, "Управление телеметрией") {
        Container(TelemetryContainer, "Сбор телеметрии")
    }

    System_Boundary(UsersSystem, "Управление пользователями") {
        Container(UsersContainer, "Администрирование пользователей")
    }

    System_Boundary(LocationsSystem, "Управление локациями") {
        Container(HousesContainer, "Администрирование домов")
        Container(LocationsContainer, "Администрирование локаций")
    }

    System_Boundary(ScenariosSystem, "Управление пользовательскими сценариями") {
        Container(ScenariosContainer, "Администрирование пользовательских сценариев")
    }

    System_Boundary(MonitoringSystem, "Мониторинг умного дома") {
        Container(AnaliticContainer, "Аналитика и отчетность")
    }
}

' --------------
' Потоки данных
' --------------

' Связи пользователей
Rel(user, WebApp, "Использует для управления умным домом")
Rel(support, WebApp, "Использует для управления пользователями и их оборудованием")
Rel(manager, WebApp, "Использует для получения информации о пользователях и их оборудовании")

' Связи интерфейсов с API
Rel(WebApp, ApiApplication, "Выполняет вызовы Api")

' Связи API
Rel(ApiApplication, db, "Обновления информации об умном доме и пользователях")
Rel(ApiApplication, DevicesContainer, "Запросы управления устройствами", "JSON")
Rel(ApiApplication, ModulesContainer, "Запросы управления модулями", "JSON")
Rel(ApiApplication, broker, "Запросы на получение телеметрии")
Rel(ApiApplication, UsersContainer, "Запросы управления пользователями", "JSON")
Rel(ApiApplication, HousesContainer, "Запросы управления домами", "JSON")
Rel(ApiApplication, LocationsContainer, "Запросы управления локациями", "JSON")
Rel(ApiApplication, ScenariosContainer, "Запросы урпавления пользовательскими сценариями", "JSON")
Rel(ApiApplication, AnaliticContainer, "Данные для аналитики")

' Связи брокера сообщений
' @todo Возможно убрать streams
Rel(broker, streams, "Потоки для обработки", "Stream")
' @todo Подумать правильно ли тут подключен брокер и должен ли он быть связан с api
Rel(broker, TelemetryContainer, "Получает ин")

' Связи системы управления телеметрией
Rel(TelemetryContainer, UserDevicesSystem, "Информация от устройств умного дома")

' Связи системы управления устройствами
' @todo Тут вопрос нужно ли их между собой связывать или можно через Api Application между ними взимодействовать
' @todo По идее Api хватит
' @todo Возможно убрать Api Application и сделать так чтобы каждый сервис сам писал в бд
' @todo В модуле управления телеметрией тогда еще будет запись в бд,
' а связь будет: ИЗ ТЕЛЕМЕТРИИ В БРОКЕР И ИЗ ТЕЛЕМЕТРИИ В БД
' Rel(DevicesContainer, UserDevicesSystem, "Запросы управления устройсвами")
' Rel(DevicesContainer, ModulesContainer, "Запросы на привязку устройств")

@enduml