# @todo Возможно сделать устройство через AsyncApi, так как нам возможно надо уведомлять всех о добавлении нового устройства
# @todo Либо сделать только часть через AsyncApi
openapi: 3.1.0
info:
  title: API управления устройствами
  description: API для создания, настройки, удаления модулей и устройств и использования функций устройств
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server

tags:
  - name: Devices
    description: Управление устройствами
  - name: DevicesFunctions
    description: Управление функциями устройств
  - name: Modules
    description: Управление модулями

paths:
  # ====================== УСТРОЙСТВА ======================
  /devices:
    get:
      tags: [Devices]
      summary: Список всех устройств
      security:
        - BearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Device"
    post:
      tags: [Devices]
      summary: Создание устройства
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceRequest"
      responses:
        200:
          description: Устройство успешно создано
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        401:
          description: Переданы некорректные данные

  /devices/{id}:
    parameters:
        - name: id
          in: path
          required: true
          description: uuid устройства
          schema:
            type: string
            format: uuid
    get:
      tags: [Devices]
      summary: Получение устройства по uuid
      security:
        - BearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        404:
          description: Устройство с заданным UUID найдено не было
    put:
      tags: [Devices]
      summary: Обновление устройства
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceRequest"
      responses:
        200:
          description: Устройство успешно обновлено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        401:
          description: Переданы некорректные данные
        404:
          description: Устройство с заданным UUID найдено не было
    delete:
      tags: [Devices]
      summary: Удаление устройства
      responses:
        200:
          description: Устройство успешно удалено # @todo Тут возможно добавить статус ответа { result: true } ...
        401:
          description: Переданы некорректные данные
        404:
          description: Устройство с заданным UUID найдено не было

# ====================== КОМПОНЕНТЫ ======================
components:
  schemas:
    # ==== Схема устройства ====
    Device:
        type: object
        properties:
          id:
            type: string
            format: uuid
            example: 550e8400-e29b-41d4-a716-446655440000
          name:
            type: string
            description: Наименование устройства
            example: Датчик дыма
          description:
            type: string
            description: Описание устройства
            example: Используется для отслеживания дыма в помещении
          serial_number:
            type: string
            description: Серийный номер устройства
            example: IMEI 35-209900-176148-1

    # ==== Схема тела создания устройства ====
    DeviceRequest:
      type: object
      required: [name, serial_number]
      properties:
        name:
          type: string
          description: Наименование устройства
          example: Датчик дыма
        serial_number:
          type: string
          description: Серийный номер устройства
          example: IMEI 35-209900-176148-1
        description:
          type: string
          description: Описание устройства
          example: Используется для отслеживания дыма в помещении

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT