@startuml API components diagram
title Диаграмма компонентов API

!include ../templates/C4_Component.puml

' Внешние сущности
Container(WebApp, "Веб-приложение", "JavaScript и выбранный фреймворк", "Веб-интерфейс для управления умным домом")
Container(UsedContainer, "Сервис к которому идет запрос")

' @todo Сюда возможно добавить обращение к сервису авторизации для проверки пользователя

' Контейнер API Gateway
Container_Boundary(TelemetryContainer, "API Gateway") {
    ' Маршрутизация запросов пользователей
    Component(RouteController, "Контроллер управления маршрутизацией запросов", "NodeJS Rest Controller")
    Component(RouteService, "Сервис управления маршрутизацией запросов", "NodeJS")
    Component(RouteComponent, "Компонент управления маршрутизацией запросов", "NodeJS")
}

' Связи маршрутизации запросов пользователей
Rel(WebApp, RouteController, "Делает запросы к api")
Rel(RouteController, RouteService, "Вызывает бизнес-логику")
Rel(RouteService, RouteComponent, "Проверяет авторизацию и перенаправляет запрос нужному сервису")
Rel(RouteComponent, UsedContainer, "Перенаправленный запрос")

@endmul