@startuml Er diagram

hide circle

!include ../templates/C4_Component.puml

' Сущности
entity "Устройство" as Device {
    + id [PK]: uuid
    name: varchar
    description: varchar
    serial_number: varchar
    type: varchar
    status: varchar
    createdAt: timestamp
    updatedAt: timestamp
}

entity "Функция устройства" as DeviceFunction {
    + id [PK]: uuid
    + deviceId [FK]: uuid
    name: varchar
    description: varchar
    command: jsonb
    createdAt: timestamp
    updatedAt: timestamp
}

entity "Модуль" as Module {
    + id [PK]: uuid
    name: varchar
    description: varchar
    createdAt: timestamp
    updatedAt: timestamp
}

entity "Связь устройств с модулями" as DMRelation {
    + id: uuid
    + deviceId: uuid
    + moduleId: uuid
}

entity "Телеметрия" as Telemetry {
    + id [PK]: uuid
    + deviceId [FK]: uuid
    data: JSONB
    createdAt: timestamp
    updatedAt: timestamp
}

entity "Пользователь" as User {  
    + id [PK]: uuid
    name: varchar
    email: varchar
    phone: varchar
}

entity "Роль" as Role {  
    + id [PK]: uuid
    name: varchar
}

entity "Связь ролей с пользователями" as RURelation {
    + id [PK]: uuid
    + userId [FK]: uuid
    + roleId [FK]: uuid
}

entity "Дом" as House {
    + id [PK]: uuid
    name: varchar
    description: varchar
    address: varchar
    createdAt: timestamp
    updatedAt: timestamp
}

entity "Связь локаций с домами" as LHRelation {
    + id [PK]: uuid
    + houseId [FK]: uuid
    + locationId [FK]: uuid
}

entity "Связь модулей с домами" as MHRelation {
    + id [PK]: uuid
    + houseId [FK]: uuid
    + moduleId [FK]: uuid
}

entity "Связь устройств с домами" as DHRelation {
    + id [PK]: uuid
    + houseId [FK]: uuid
    + deviceId [FK]: uuid
}

entity "Локация" as Location {
    + id [PK]: uuid
    name: varchar
    description: varchar
    type: varchar
    createdAt: timestamp
    updatedAt: timestamp
}

entity "Связь модулей с локациями" as MLRelation {
    + id [PK]: uuid
    + moduleId [FK]: uuid
    + locationId [FK]: uuid
}

entity "Связь устройств с локациями" as DLRelation {
    + id [PK]: uuid
    + deviceId [FK]: uuid
    + locationId [FK]: uuid
}

entity "Пользовательский сценарий" as Scenario {
    + id [PK]: uuid
    + name: varchar
    + description: varchar
    + command jsonb
    + conditions jsonb
}

entity "Связь домов с пользовательскими сценариями" as HSRelation {
    + id [PK]: uuid
    + scenarioId [FK]: uuid
    + houseId [FK]: uuid
}

entity "Связь локаций с пользовательскими сценариями" as LSRelation {
    + id [PK]: uuid
    + scenarioId [FK]: uuid
    + locationId [FK]: uuid
}

entity "Связь модулей с пользовательскими сценариями" as MSRelation {
    + id [PK]: uuid
    + scenarioId [FK]: uuid
    + moduleId [FK]: uuid
}

entity "Связь устройств с пользовательскими сценариями" as DSRelation {
    + id [PK]: uuid
    + scenarioId [FK]: uuid
    + deviceId [FK]: uuid
}

entity "Связь пользователей с пользовательскими сценариями" as USRelation {
    + id [PK]: uuid
    + scenarioId [FK]: uuid
    + userId [FK]: uuid
}

' Связи устройств
Device ||--o{ DeviceFunction
Device ||--o{ DMRelation
Device ||--o{ Telemetry
Device ||--|| DHRelation
Device ||--|| DLRelation
Device }o--o{ DSRelation

' Связи модулей
Module ||--o{ DMRelation
Module }o--|| MHRelation
Module }o--|| MLRelation
Module }o--o{ MSRelation

' Связи пользователей
User ||--o{ RURelation
User ||--o{ USRelation

' Связи ролей
Role }o--o{ RURelation

' Связи домов
House ||--o{ LHRelation
House ||--o{ MHRelation
House ||--o{ DHRelation
House }o--o{ HSRelation

' Связи локаций
Location }o--|| LHRelation
Location ||--o{ MLRelation
Location ||--o{ DLRelation
Location }o--o{ LSRelation

' Связи пользовательских сценариев
Scenario }o--o{ HSRelation
Scenario }o--o{ LSRelation
Scenario ||--o{ MSRelation
Scenario ||--o{ DSRelation
Scenario ||--o{ USRelation
@enduml